### ISSUE TITLE
IMSDK.zip 下载的压缩包有问题

### ISSUE THREAD

**Issue by SciMagic** [zhaoyang21cn/iLiveSDK_Mac_Suixinbo#3]
LoadSDK.sh    IMSDKSDKVersion="IMSDK_2.7.2.14050.13860"
console log: 
|-------------------------------unzip IMSDK-------------------------------------|
Archive:  IMSDK.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of IMSDK.zip or
        IMSDK.zip.zip, and cannot find IMSDK.zip.ZIP, period.
|-------------------------------unzip AVSDK-------------------------------------

**Comment by chaobaji** [comment]
应该修改为   IMSDKSDKVersion="IMSDK_MAC_2.7.2.14050.13860"
